### ISSUE TITLE
Problem with showCupertinoModalBottomSheet and pushAndRemoveUntil

### ISSUE THREAD

**Issue by marcosmko** [jamesblasco/modal_bottom_sheet#75]
Hello all!

First, congratulations on making this amazing framework!

I would like to report a bug when using the method `pushAndRemoveUntil`.
When I use `showCupertinoModalBottomSheet`, then (inside) navigate to another page using `pushAndRemoveUntil`, and then popping up, it causes the following error:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator(dirty, dependencies: [_EffectiveTickerMode, HeroControllerScope], state: NavigatorState#4ab49(tickers: tracking 0 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4081 pos 12: '_history.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Navigator file:///Users/marcoskobuchi/Desktop/modal_bottom_sheet/example/lib/modals/modal_with_navigator.dart:11:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:4081:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4681:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4564:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4737:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4280:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel unknown, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.21.0-9.2.pre at /Users/marcoskobuchi/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/marcoskobuchi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/marcoskobuchi/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/marcoskobuchi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

```

</details>

To reproduce this error, substitute the following code (line 29-37 of `modal_with_navigator.dart`):
```
Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => CupertinoPageScaffold(
                                      navigationBar: CupertinoNavigationBar(
                                        middle: Text('New Page'),
                                      ),
                                      child: Stack(
                                        fit: StackFit.expand,
                                        children: <Widget>[],
                                      ))));
```

with:

```
Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(
                                  builder: (context) => CupertinoPageScaffold(
                                      navigationBar: CupertinoNavigationBar(
                                        middle: Text('New Page'),
                                      ),
                                      child: Stack(
                                        fit: StackFit.expand,
                                        children: <Widget>[
                                          MaterialButton(
                                            onPressed: () => Navigator.of(context).pop(),
                                            child: Text('touch here'),
                                          )
                                        ],
                                      )
                                  )
                              ), ModalRoute.withName('/'));
```

Am I missing something here?

**Comment by jamesblasco** [comment]
Yess, what are you trying to pop? Is the modal>

When you call
```dart
Navigator.of(context).pop();
```

It will try to close the navigator inside the modal, leaving no routes in that navigator.
So when the Navigator updates, it will give an error as no routes are available to load.
